# ENV: SIT

server:
    port: 8080
    servlet:
        context-path: /SpringBootDemo
        session:
            cookie:
                name: JSESSIONID
                domain: zero.com
                path: /
                http-only: false
                secure: false
                max-age: -1

# start DB server, java -jar "H:/lib/java/h2-1.4.197.jar"
# multipart which refer to MultipartProperties
spring:
    datasource:
        # type: org.apache.tomcat.jdbc.pool.DataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/pim?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&useSSL=false
        username: root
        password: root

    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 200MB

appconf:
    config-path: /SpringBootDemo/conf/
    version: 20180705001

# driver-class-name: com.mysql.jdbc.Driver
# url: jdbc:mysql://10.77.163.2:3307/SiteSolution?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true
# url: jdbc:h2:~/H2DB-SpringRestDemo
# url: jdbc:h2:tcp://localhost/~/H2DB-SpringRestDemo

# driver-class-name: org.h2.Driver
# jdbc:h2:tcp://localhost/~/H2DB-SpringRestDemo
# username: sa
# password: sa